baseURL = 'https://bravepuffin.com'
languageCode = 'en-us'
title = 'Brave Puffin'
pagination.pagerSize = 10
theme = 'maverick'
googleAnalytics = 'G-42NQX112R9'

[permalinks]
  pages = "/:slug"

[params]
  logo = 'favicon.ico'
  description = "Solar powered, long range autonomous boat"
  author = '...'

  [params.comments]
    enabled = true
    githubRepo = 'sla256/brave-puffin-com'
    theme = 'github-light'


[menu]
  [[menu.main]]
    identifier = "contact"
    name = "Contact"
    url = "/contact/"
    weight = 2

  [[menu.main]]
    identifier = "posts"
    name = "Posts"
    url = "/posts/"
    weight = 1


[markup]
  [markup.goldmark.renderer]
    unsafe = true
  [markup.highlight]
    anchorLineNos = false
    codeFences = true
    guessSyntax = false
    hl_Lines = ''
    hl_inline = false
    lineAnchors = ''
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = true
    noHl = false
    style = 'monokailight'
    tabWidth = 4

[taxonomies]
  tag = "tags"

[outputs]
  home = ["HTML", "RSS", "JSON"]
  section = ["HTML"]

[outputFormats.RSS]
  mediatype = "application/rss"
  baseName = "atom"

[outputFormats.JSON]
  mediatype = "application/json"
  baseName = "feed"

ignoreErrors = ["error-remote-getjson"]
